name: z
channels:
  - ome
  - conda-forge
  - defaults
dependencies:
  - flake8
  - ipython
  - mypy
  - omero-py
  - pip
  - pytest
  - requests
  - s3fs
  - scikit-image
  - scipy
  - xarray
  - zarr >= 2.4.0
  - pip:
      - pre-commit
# python.app -- only install on OSX:
# sys_platform environment marker doesn't work in environment.yml
