name: Dispatch

on:
  push:
    branches:
      - master
  #  types: [closed]

jobs:
  dispatch:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['ome/ome_zarr_test_suite']
    env:
      event_dispatch: run_test_suite
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # yamllint disable rule:line-length
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_API_TOKEN }}
          event-type: ${{ env.event_dispatch }}
          repository: ${{ matrix.repo }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "repo": "${{ github.repository }}", "owner": "${{github.repository_owner}}", "number": "${{github.event.number}}"}'
